### PR TITLE
Fix support comprehensions inside functions when use strict_undefined…

### LINKED ISSUE #398: Accessing an attribute or an index in a dictionnary comprehension trigger an error with the mako version 1.3.3
Here is an example

```python
from mako.template import Template

text = """
<%
    mydict = { 'foo': 1 }

    def getkeys(x):
        return { k[0]: 0 for k in x.keys() }
%>

${ ','.join( getkeys(mydict) ) }
"""

tmpl = Template(text=text, strict_undefined=True)
out = tmpl.render()
print(out)
```

This produces the following error:

```
Traceback (most recent call last):
  File "/home/sgr/Programmation/mako/test3.py", line 16, in <module>
    tmpl = Template(text=text, strict_undefined=True)
  File "/home/sgr/Programmation/mako/mako/template.py", line 299, in __init__
    (code, module) = _compile_text(self, text, filename)
  File "/home/sgr/Programmation/mako/mako/template.py", line 676, in _compile_text
    source, lexer = _compile(
  File "/home/sgr/Programmation/mako/mako/template.py", line 656, in _compile
    node = lexer.parse()
  File "/home/sgr/Programmation/mako/mako/lexer.py", line 248, in parse
    if self.match_python_block():
  File "/home/sgr/Programmation/mako/mako/lexer.py", line 404, in match_python_block
    self.append_node(
  File "/home/sgr/Programmation/mako/mako/lexer.py", line 129, in append_node
    node = nodecls(*args, **kwargs)
  File "/home/sgr/Programmation/mako/mako/parsetree.py", line 158, in __init__
    self.code = ast.PythonCode(text, **self.exception_kwargs)
  File "/home/sgr/Programmation/mako/mako/ast.py", line 47, in __init__
    f.visit(expr)
  File "/home/sgr/Programmation/mako/mako/_ast_util.py", line 136, in visit
    return self.generic_visit(node)
  File "/home/sgr/Programmation/mako/mako/_ast_util.py", line 144, in generic_visit
    self.visit(item)
  File "/home/sgr/Programmation/mako/mako/_ast_util.py", line 135, in visit
    return f(node)
  File "/home/sgr/Programmation/mako/mako/pyparser.py", line 91, in visit_FunctionDef
    self._visit_function(node, False)
  File "/home/sgr/Programmation/mako/mako/pyparser.py", line 138, in _visit_function
    self.visit(n)
  File "/home/sgr/Programmation/mako/mako/_ast_util.py", line 136, in visit
    return self.generic_visit(node)
  File "/home/sgr/Programmation/mako/mako/_ast_util.py", line 146, in generic_visit
    self.visit(value)
  File "/home/sgr/Programmation/mako/mako/_ast_util.py", line 135, in visit
    return f(node)
  File "/home/sgr/Programmation/mako/mako/pyparser.py", line 107, in visit_DictComp
    self.visit(node.elt)
AttributeError: 'DictComp' object has no attribute 'elt'
```

I am running Python 3.10.12 and Mako 1.3.3. It was working with Mako 1.3.2.

### PR DESCRIPTION
**Pull request by sgranjoux**
… flag

Fixes: https://github.com/sqlalchemy/mako/issues/398

The element or key and value used respectively in list/set comprehension and dictionary comprehension cannot be used to declare identifiers so no need to visit them.

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision a52802b935e038a4651dbc0a06384eb7471793bd of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change a52802b935e038a4651dbc0a06384eb7471793bd: https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/5322

**Comment by zzzeek** [comment]
thanks!

**Comment by sgranjoux** [comment]
I have added an test failing with version 1.3.3.

I think the first issue is that an AST node representing a dictionnary comprehension hasn't a attribute `elt` but `key` and `value` instead so the line https://github.com/sgranjoux/mako/blob/af80cbd71c2e68954310c4b06f4514f6718d2575/mako/pyparser.py#L107 is wrong. It's should be at least `node.key` instead of `node.elt`.

But this doesn't fix the initial issue if `node.elt`, `node.key` or `node.value` is not a `Name` but a `Subscript` like in my new test or an `BinOp` like in the test already in the regression. I think we just need to skip these nodes.

I was just an user of the mako library and I have spent just a few hours trying to fix this issue. @cocolato can you take look at this?

It's my first pull request. I have just seen that some things are failing, I will check that.

**Comment by sgranjoux** [comment]
I don't know why 2 of the checks above are failing. Should I add a `doc/build/unreleased/398.rst` file?

**Comment by zzzeek** [comment]
pep8 failures you can address if you install pre commit:

```
pre-commit install
pre-commit run
```

**Comment by zzzeek** [comment]
also sure changeset file would be very helpful thanks!

**Comment by sgranjoux** [comment]
I have added a changeset file and the commit hooks but they don't report any failures.

**Comment by zzzeek** [comment]
oh, this is a new thing in flake8 that we are disabling, sorry

please add this

```diff
diff --git a/setup.cfg b/setup.cfg
index f643d01..ecbbe0f 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -89,7 +89,7 @@ show-source = true
 enable-extensions = G
 # E203 is due to https://github.com/PyCQA/pycodestyle/issues/373
 ignore =
-    A003,
+    A003,A005
     D,
     E203,E305,E711,E712,E721,E722,E741,
     N801,N802,N806,

```

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision d708e27f988da7e1923a1a9dab90a0884ef84bbb of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset d708e27f988da7e1923a1a9dab90a0884ef84bbb added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/5322

**Comment by zzzeek** [comment]
i dont get any ping when code is updated.....running again

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/5322 has been **merged**. Congratulations! :)
