### ISSUE TITLE
1.1.4: setuptools build_sphinx target fails

### ISSUE THREAD

**Issue by kloczek** [sqlalchemy/mako#331]
```console
+ /usr/bin/python3 setup.py build_sphinx -b man
running build_sphinx
Running Sphinx v4.0.2
/usr/lib64/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
making output directory... done
WARNING: html_static_path entry 'static' does not exist

Extension error (zzzeeksphinx.scss):
Handler <function add_stylesheet at 0x7fbb5591f3a0> for event 'builder-inited' threw an exception (exception: 'Sphinx' object has no attribute 'add_stylesheet')
error: Bad exit status from /var/tmp/rpm-tmp.6dtk5R (%build)
```

**Comment by zzzeek** [comment]
https://github.com/sqlalchemyorg/zzzeeksphinx/issues/5

**Comment by kloczek** [comment]
Just upgraded `zzzeeksphinx` to 1.1.4 and still build_shinx fails :(
```console
[tkloczko@barrel mako-rel_1_1_4]$ /usr/bin/python3 setup.py build_sphinx -b man
running build_sphinx
Running Sphinx v4.0.2
/usr/lib64/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
making output directory... done
WARNING: html_static_path entry 'static' does not exist
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 11 added, 0 changed, 0 removed
The name of the builder is: manThe name of the builder is: man
Extension error (sphinx_paramlinks.sphinx_paramlinks):
Handler <function build_index at 0x7f5b36f8f8b0> for event 'doctree-read' threw an exception (exception: __new__() missing 1 required positional argument: 'aliased')
[tkloczko@barrel SPECS]$ pip show zzzeeksphinx
Name: zzzeeksphinx
Version: 1.2.3
Summary: Zzzeek's Sphinx Layout and Utilities.
Home-page: https://github.com/sqlalchemyorg/zzzeeksphinx
Author: Mike Bayer
Author-email: mike@zzzcomputing.com
License: MIT
Location: /usr/lib/python3.8/site-packages
Requires: pyscss, mako, requests
Required-by:
```

**Comment by zzzeek** [comment]
can't reproduce, steps to build:

```
$ cd ~/tmp/foo/
$  virtualenv .venv
$ git clone https://github.com/sqlalchemy/mako 
$  cd mako/
$  cd doc/build/
$  ~/tmp/foo/.venv/bin/pip install -r requirements.txt 
$  source ~/tmp/foo/.venv/bin/activate
$  make html
```

output:

```
[classic@photon3 foo]$ git clone https://github.com/sqlalchemy/mako 
Cloning into 'mako'...
remote: Enumerating objects: 6675, done.
remote: Counting objects: 100% (161/161), done.
remote: Compressing objects: 100% (129/129), done.
remote: Total 6675 (delta 70), reused 105 (delta 18), pack-reused 6514
Receiving objects: 100% (6675/6675), 1.21 MiB | 9.18 MiB/s, done.
Resolving deltas: 100% (4664/4664), done.
[classic@photon3 foo]$ cd mako/
[classic@photon3 mako:master]$ cd doc/build/
[classic@photon3 build:master]$ ~/tmp/foo/.venv/bin/pip install -r requirements.txt 
Collecting changelog
  Cloning https://github.com/sqlalchemyorg/changelog.git to /tmp/pip-install-db2ji9j_/changelog_f93b61322b8547e6a235d649834d896a
  Running command git clone -q https://github.com/sqlalchemyorg/changelog.git /tmp/pip-install-db2ji9j_/changelog_f93b61322b8547e6a235d649834d896a
Collecting sphinx-paramlinks
  Cloning https://github.com/sqlalchemyorg/sphinx-paramlinks.git to /tmp/pip-install-db2ji9j_/sphinx-paramlinks_ad9e8b46743a441d866613a7f8a6e18a
  Running command git clone -q https://github.com/sqlalchemyorg/sphinx-paramlinks.git /tmp/pip-install-db2ji9j_/sphinx-paramlinks_ad9e8b46743a441d866613a7f8a6e18a
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting zzzeeksphinx
  Cloning https://github.com/sqlalchemyorg/zzzeeksphinx.git to /tmp/pip-install-db2ji9j_/zzzeeksphinx_bbfba011588a49568616ec45ba947fc4
  Running command git clone -q https://github.com/sqlalchemyorg/zzzeeksphinx.git /tmp/pip-install-db2ji9j_/zzzeeksphinx_bbfba011588a49568616ec45ba947fc4
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pyscss
  Using cached pyScss-1.3.7-cp39-cp39-linux_x86_64.whl
Collecting requests
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting mako
  Using cached Mako-1.1.4-py2.py3-none-any.whl (75 kB)
Requirement already satisfied: MarkupSafe>=0.9.2 in /home/classic/tmp/foo/.venv/lib64/python3.9/site-packages (from mako->zzzeeksphinx->-r requirements.txt (line 3)) (1.1.1)
Requirement already satisfied: six in /home/classic/tmp/foo/.venv/lib/python3.9/site-packages (from pyscss->zzzeeksphinx->-r requirements.txt (line 3)) (1.15.0)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Building wheels for collected packages: changelog, sphinx-paramlinks, zzzeeksphinx
  Building wheel for changelog (setup.py) ... done
  Created wheel for changelog: filename=changelog-0.5.5-py3-none-any.whl size=16160 sha256=8b4d8b735fab69269e237c67a84a13504f509b6b741eeded02e235637db11c3b
  Stored in directory: /tmp/pip-ephem-wheel-cache-0x_3ac5p/wheels/45/3c/77/26df1a5522ca5ac1062f81cf3a8983ae7f39f057099c2f6a39
  Building wheel for sphinx-paramlinks (PEP 517) ... done
  Created wheel for sphinx-paramlinks: filename=sphinx_paramlinks-0.5.1-py3-none-any.whl size=8706 sha256=64f6f8b92f4cc8a8ef749e15d44ee219c19619a317f11e8efb9cb7540f7144c7
  Stored in directory: /tmp/pip-ephem-wheel-cache-0x_3ac5p/wheels/a1/8d/c5/4c0bfbb8ef083a00963761bed2b1259f6d71a21e5851d51d5b
  Building wheel for zzzeeksphinx (PEP 517) ... done
  Created wheel for zzzeeksphinx: filename=zzzeeksphinx-1.2.3-py3-none-any.whl size=77686 sha256=bfcca37119f3c93f7ece4eb0204f726dfbb2e558ece3e697a886d29812429c0a
  Stored in directory: /tmp/pip-ephem-wheel-cache-0x_3ac5p/wheels/86/9e/c5/a0b0162d03ebbfdb1600693eb565bb5c20fd41edf8168822c3
Successfully built changelog sphinx-paramlinks zzzeeksphinx
Installing collected packages: urllib3, idna, chardet, certifi, requests, pyscss, mako, zzzeeksphinx, sphinx-paramlinks, changelog
Successfully installed certifi-2021.5.30 changelog-0.5.5 chardet-4.0.0 idna-2.10 mako-1.1.4 pyscss-1.3.7 requests-2.25.1 sphinx-paramlinks-0.5.1 urllib3-1.26.5 zzzeeksphinx-1.2.3
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the '/home/classic/tmp/foo/.venv/bin/python -m pip install --upgrade pip' command.
[classic@photon3 build:master]$ source ~/tmp/foo/.venv/bin/activate
(.venv) [classic@photon3 build:master]$ make html
sphinx-build -b html -A mako_layout=html -d output/doctrees  -T . output/html
Running Sphinx v4.0.0
/home/classic/.venv3/lib64/python3.9/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
making output directory... done
WARNING: html_static_path entry 'static' does not exist
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 11 source files that are out of date
updating environment: [new config] 11 added, 0 changed, 0 removed
reading sources... [100%] usage                                                                                                            
/home/classic/tmp/foo/mako/doc/build/changelog.rst:886: WARNING: Unknown target name: "cache".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] usage                                                                                                             
/home/classic/tmp/foo/mako/doc/build/caching.rst:136: WARNING: py:class reference target not found: beaker.cache.CacheManager
/home/classic/tmp/foo/mako/doc/build/caching.rst:225: WARNING: py:mod reference target not found: dogpile.cache.plugins.mako_cache
/home/classic/tmp/foo/mako/mako/cache.py:docstring of mako.cache.Cache:13: WARNING: py:attr reference target not found: Template.cache
docstring of mako.runtime.Namespace.uri:5: WARNING: py:attr reference target not found: Template.uri
docstring of mako.runtime.TemplateNamespace.uri:5: WARNING: py:attr reference target not found: Template.uri
/home/classic/tmp/foo/mako/mako/runtime.py:docstring of mako.runtime.LoopContext:7: WARNING: py:attr reference target not found: parent
/home/classic/tmp/foo/mako/mako/runtime.py:docstring of mako.runtime.LoopContext:9: WARNING: py:attr reference target not found: index
/home/classic/tmp/foo/mako/mako/runtime.py:docstring of mako.runtime.LoopContext:11: WARNING: py:attr reference target not found: reverse_index
/home/classic/tmp/foo/mako/mako/runtime.py:docstring of mako.runtime.LoopContext:13: WARNING: py:attr reference target not found: first
/home/classic/tmp/foo/mako/mako/runtime.py:docstring of mako.runtime.LoopContext:15: WARNING: py:attr reference target not found: last
/home/classic/tmp/foo/mako/mako/runtime.py:docstring of mako.runtime.LoopContext:17: WARNING: py:attr reference target not found: even
/home/classic/tmp/foo/mako/mako/runtime.py:docstring of mako.runtime.LoopContext:21: WARNING: py:attr reference target not found: odd
/home/classic/tmp/foo/mako/doc/build/usage.rst:143: WARNING: py:class reference target not found: TopLevelNotFound
/home/classic/tmp/foo/mako/doc/build/usage.rst:358: WARNING: py:mod reference target not found: mako.ext.pygmentplugin
/home/classic/tmp/foo/mako/mako/template.py:docstring of mako.template.Template:184: WARNING: py:class reference target not found: Lexer
/home/classic/tmp/foo/mako/mako/template.py:docstring of mako.template.Template:184: WARNING: py:class reference target not found: Lexer
/home/classic/tmp/foo/mako/mako/lookup.py:docstring of mako.lookup.TemplateCollection.get_template:4: WARNING: py:class reference target not found: TemplateLookupException
generating indices... genindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 19 warnings.

The HTML pages are in output/html.
The name of the builder is: htmlCopying sphinx_paramlinks stylesheet... done
The name of the builder is: htmlCopying sphinx_paramlinks stylesheet... done

Build finished. The HTML pages are in output/html.
```

**Comment by zzzeek** [comment]
works with sphinx 4.0.2 also

**Comment by zzzeek** [comment]
your error message is in sphinx_paramlinks:

```
Extension error (sphinx_paramlinks.sphinx_paramlinks):
Handler <function build_index at 0x7f5b36f8f8b0> for event 'doctree-read' threw an exception (exception: __new__() missing 1 required positional argument: 'aliased')

```

make sure you are on 0.5.1

**Comment by kloczek** [comment]
> make sure you are on 0.5.1

And that was key point of the equation..
Thx
